name: CI Workflow - Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t task-manager:latest .

      - name: Run Docker Container
        run: docker run --rm -e GITHUB_USER="${{ github.actor }}" task-manager:latest
