name: GitHub Projects Automation

on:
  pull_request:
    types: [closed]

jobs:
  move-issue-to-done:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

    

      - name: Move Issue from ToDo to Done
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'Closes #\K\d+')

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No 'Closes #IssueNumber' found in PR description. Skipping issue movement."
            exit 0
          fi

          echo "Found issue #$ISSUE_NUMBER linked to this PR."

          PROJECT_ID="PVT_kwHODLrPW84A6CD6"
          DONE_COLUMN_ID="98236657"
          STATUS_FIELD_ID="PVTSSF_lAHODLrPW84A6CD6zguunb8"

          ISSUE_NODE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                               -H "Accept: application/vnd.github.v3+json" \
                               "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER" | jq -r '.node_id')

          if [ -z "$ISSUE_NODE_ID" ]; then
            echo "Could not find node ID for issue #$ISSUE_NUMBER. Skipping."
            exit 1
          fi

          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "GraphQL-Features: projects_next_graphql" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d '{
              "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'${PROJECT_ID}'\", itemId: \"'${ISSUE_NODE_ID}'\", fieldId: \"'${STATUS_FIELD_ID}'\", value: { singleSelectOptionId: \"'${DONE_COLUMN_ID}'\" } }) { clientMutationId } }"
            }'
          echo "Issue #$ISSUE_NUMBER moved to 'Done' column in project board."